server:
  port: 8090
spring:
  application:
    name: infoService
  cloud:
    nacos:
      server-addr: localhost:8848
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://mysql.sqlpub.com:3306/mysqlnene
  #   username: neneneru
  #   password: 8329a4fa1f76e1f1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neneneru
    username: root
    password: Nene0720
    hikari:
      maximum-pool-size: 24
  rabbitmq:
    host: 127.0.0.1
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    listener:
      simple:
        concurrency: 24 # 消费者个数
        max-concurrency: 30 # 最大消费者个数
        prefetch: 250
